### ISSUE TITLE
ERROR: An error occurred retrieving the selected regions Sagemaker Endpoints:

### ISSUE THREAD

**Issue by jhuan015** [awslabs/amazon-sagemaker-inference-client#12]
Hi,

I'm getting a few errors trying to run this. I followed the readme and have a Sagemaker endpoint running on US-East-2. The dropdown for Endpoint Name is empty:
![image](https://user-images.githubusercontent.com/3654724/139011287-338bd6ef-c97d-4706-a612-1144d4c8b7db.png)

and i'm also getting the API error: `API smInferenceClient does not exist undefined`.

when running `amplify add api`, I followed the instructions in the readme and it looks okay in AWS?
![Screenshot 2021-10-26 232833](https://user-images.githubusercontent.com/3654724/139011594-af70003f-c9ce-468a-856c-5cc02519a75f.png)

Please let me know if I'm missing anything. Thanks!

**Comment by dcolcott** [comment]
Hi Jonathan, apologies in the delayed response. if you don't have the smInferenceClient API then the Amplify deployment must have failed for some reason. This would explain the missing Sagemaker endpoint as it can't request the information from the client side. 

I have just udated to the latest Amplify CLI version and updated the dependencies. Can I suggest you try the deployment again and check things like your AWS permissions and watch the output form Amplify to see if it gives you any more information as to why the API is not being deployed.
